version: '3.7'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/docker/Dockerfile.jvm
    ports:
      - '${AUTH_SERVICE_PORT:-8080}:8080'
    depends_on:
      - db
  recording-service:
    build:
      context: .
      dockerfile: recording-service/docker/Dockerfile.jvm
    ports:
      - '${RECORDING_SERVICE_PORT:-8081}:8080'
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - '${POSTGRES_PORT:-5400}:5432'
    environment:
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_HOST=${DATABASE_HOST:-localhost}
