version: '3.7'

services:
  auth-service:
    build:
      context: ..
      dockerfile: auth-service/docker/Dockerfile.jvm
    ports:
      - '${AUTH_SERVICE_PORT:-8080}:8080'
    environment:
      - POSTGRES_HOST=db
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - auth-service-migrations
  auth-service-migrations:
    build:
      context: ../auth-service/migrations
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  beacon-service:
    build:
      context: ..
      dockerfile: beacon-service/docker/Dockerfile.jvm
    ports:
      - '${RECORDING_SERVICE_PORT:-8081}:8080'
    depends_on:
      - beacon-service-migrations
  beacon-service-migrations:
    build:
      context: ../beacon-service/migrations
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  db:
    image: postgres:11
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command:
      ['sh', '-c', 'bin/zookeeper-server-start.sh config/zookeeper.properties']
    ports:
      - '2181:2181'
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command:
      [
        'sh',
        '-c',
        'bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}',
      ]
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      LOG_DIR: '/tmp/logs'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.type: single-node
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    volumes:
      - source: $HOME/pipelines
        target: /usr/share/logstash/pipeline
        type: bind
    ports:
      - '12201:12201/udp'
      - '5000:5000'
      - '9600:9600'
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - '5601:5601'
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
