print('Hello Tiltfile')

k8s_yaml('k8/base.yml')

k8s_yaml(kustomize('../auth/auth-api/k8/overlays/minikube'))
k8s_resource('auth-api', port_forwards=8080)
docker_build('eu.gcr.io/insight/auth-api', '..', {}, '../auth/auth-api/docker/Dockerfile.jvm')

k8s_yaml('../auth/auth-api/migrations/manifests.yaml')
docker_build('eu.gcr.io/insight/auth-api-migrations', '../auth/auth-api/migrations', {})

k8s_yaml(kustomize('../beacon/api/k8/overlays/development'))
k8s_resource('beacon-api', port_forwards=8081)
docker_build('eu.gcr.io/insight/beacon-api', '..', {}, '../beacon/api/docker/Dockerfile.jvm')

k8s_yaml(kustomize('../session/session-api/k8/overlays/development'))
k8s_resource('session-api', port_forwards=8082)
docker_build('eu.gcr.io/insight/session-api', '..', {}, '../session/session-api/docker/Dockerfile.jvm')

k8s_yaml('../session/session-api/migrations/manifests.yaml')
docker_build('eu.gcr.io/insight/session-api-migrations', '../session/session-api/migrations', {})

k8s_yaml(kustomize('../../frontend/app/k8/overlays/development'))
k8s_resource('app', port_forwards=3000)
docker_build('eu.gcr.io/insight/app', '../..', {}, '../../frontend/app/docker/Dockerfile')
