apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/insight/beacon
          name: api
          imagePullPolicy: Never
