backend:
  type: es
  es:
    host: elasticsearch-master

parsers:
  enabled: true
  json:
    - name: json
      extraEntries: |-
       Time_Key    time
       Time_Format %Y-%m-%dT%H:%M:%S.%L
       Time_Keep   On
       Decode_Field_As escaped_utf8 log do_next
       Decode_Field_As json log
