---
environments:
  default:
    values:
      - ./default.yaml
    missingFileHandler: Error
  production:
    values:
      - ./production.yaml
    missingFileHandler: Error

repositories:
  # To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co

releases:
  - name: postgres
    chart: bitnami/postgresql
    namespace: { { requiredEnv "namespace" } }
    values:
      - postgres.yaml
  - name: kafka
    chart: bitnami/kafka
    namespace: { { requiredEnv "namespace" } }
    values:
      - kafka.yaml
  - name: es3
    chart: elastic/elasticsearch
    namespace: { { requiredEnv "namespace" } }
    values:
      - es.yaml
  - name: letsencrypt
    chart: ./letsencrypt
    namespace: cert-manager
    values:
      - apiKey: { { .Values.cfApiKey } }
      - email: { { .Values.cfEmail } }
