apiVersion: apps/v1
kind: Deployment
metadata:
  name: recording-service
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/insight/recording-service
          name: recording-service
          imagePullPolicy: Never