---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    team: auth
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: auth
  labels:
    team: auth
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
