version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: page-service/src/main/docker/Dockerfile.jvm
    ports:
      - '8080:${PORT:-8080}'
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - '5400:${DATABASE_PORT:-5432}'
    environment:
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_HOST=${DATABASE_HOST:-localhost}