---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-api
  namespace: recording
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/insight/session-api
          name: session-api
          imagePullPolicy: Never
