---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/insight/app
          name: app
          imagePullPolicy: Never
