apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: beacon-service
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beacon-service
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
