apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recording
commonLabels:
  team: recording
  app: beacon-service
resources:
  - service.yaml
  - deployment.yaml
  - horizontal-pod-autoscaler.yaml
