---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
type: Opaque
stringData:
  client_id: 237859759623-rfpiq8eo37afp0qc294ioqrjtq17q25h.apps.googleusercontent.com
  client_secret: 2e4u1VcV24Hi_UsHA0kIJIzr
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  username: postgres
  password: postgres
