---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recording
commonLabels:
  team: recording
  app: beacon-api
resources:
  - service.yaml
  - deployment.yaml
  - hpa.yaml
