---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: recording
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/insight/auth-api
          name: auth-api
          imagePullPolicy: Never
