---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
  namespace: recording
  labels:
    team: auth
type: Opaque
stringData:
  client_id: 237859759623-3skn6doo7bcm1gg6356uf2cq1djrm924.apps.googleusercontent.com
  client_secret: 06nA-yBVowqETJh5mRRwCCB8
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: recording
  labels:
    team: auth
type: Opaque
stringData:
  username: postgres
  password: postgres
