on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkstyleMain checkstyleTest --parallel
          build-root-directory: backend
          wrapper-directory: backend
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
          shopt -s globstar
          cat backend/**/reports/checkstyle/main.xml | ./bin/reviewdog -name="checkstyle" -f=checkstyle -reporter=github-pr-check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test --continue jacocoTestReport
          build-root-directory: backend
          wrapper-directory: backend
        env:
          DOCKER_BUILDKIT: 1
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-reports
          path: backend/**/build/reports/**
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: backend/**/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
