---
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend:check.yml'

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: pmdMain pmdTest --parallel
          build-root-directory: backend
          wrapper-directory: backend
      - name: Merge reports
        run: |
          sudo apt-get install zsh
          head -n 5 backend/auth/auth-api/build/reports/pmd/main.xml > report.xml
          zsh -c 'for file in backend/**/build/reports/pmd/main.xml;do;cat "$file" | tail -n +3 | sed "$ d" >> report.xml;done'
          tail -n 1 backend/auth/auth-api/build/reports/pmd/main.xml >> report.xml
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.xml | reviewdog -f=checkstyle -reporter=github-pr-check

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkstyleMain checkstyleTest --parallel
          build-root-directory: backend
          wrapper-directory: backend
      - name: Merge reports
        run: |
          sudo apt-get install zsh
          head -n 2 backend/auth/auth-api/build/reports/checkstyle/main.xml > report.xml
          zsh -c 'for file in backend/**/build/reports/checkstyle/main.xml;do;cat "$file" | tail -n +3 | sed "$ d" >> report.xml;done'
          tail -n 1 backend/auth/auth-api/build/reports/checkstyle/main.xml >> report.xml
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.xml | reviewdog -f=checkstyle -reporter=github-pr-check
