on:
  push:
    paths:
      - 'browser/**'
      - '.github/workflows/browser.yml'

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: lerna bootstrap, lint and unit test
        run: |
          npx lerna bootstrap
          yarn lint
          yarn test:coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: browser
      - name: build
        run: |
          yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: tracking-dist
          path: browser/tracking/dist

  deploy:
    name: Deploy scripts to CDN
    runs-on: ubuntu-latest
    needs: [lint_test_build]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: tracking-dist
      - run: ls -a
      - run: cat tracking-dist/index.js
