on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          path: ./core
      - uses: MrRamych/gradle-actions/openjdk-13@3.1
        with:
          args: test
