on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MrRamych/gradle-actions/openjdk-13@3.1
        working-directory: core
        with:
          args: test
