---
on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/frontend:preview.yml'
      - 'frontend/app/**'
      - 'frontend/try/**'
      - 'frontend/shared/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'

env:
  CI: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
