on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/browser.yml'

jobs:
  lint_test_build:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: lerna bootstrap, lint and unit test
        run: |
          npx lerna bootstrap
          yarn lint
          yarn test:coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: browser
      - name: build
        run: |
          yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: s
          path: browser/tracking/dist

  deploy:
    name: Deploy scripts to CDN
    runs-on: ubuntu-latest
    needs: [lint_test_build]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: s
          path: deployment/s
      - name: Prepare files for deployment
        run: |
          mv deployment/s/insight.js.gz deployment/s/insight.js
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --content-encoding gzip
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'deployment'
